### ISSUE TITLE
Erro lab.create()

### ISSUE THREAD

**Issue by nguyentheanhhnd** [davidban77/gns3fy#117]
I try run script: 
```from gns3fy import Gns3Connector, Project

server = Gns3Connector(url="http://localhost:3080")
lab = Project(name="check", connector=server)
try:
    lab.create()
    print("Project created successfully")
except ValueError as e:
    print(f"Error creating project: {e}")
print(server.projects_summary())
print(lab.status)
```
this is erro :
python3 vidu2.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gns3fy/gns3fy.py", line 141, in http_call
    _response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:3080/v2/projects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vidu2.py", line 12, in <module>
    lab.create()
  File "/usr/local/lib/python3.8/dist-packages/gns3fy/gns3fy.py", line 1264, in create
    _response = self.connector.http_call("post", _url, json_data=data)
  File "/usr/local/lib/python3.8/dist-packages/gns3fy/gns3fy.py", line 143, in http_call
    raise HTTPError(
requests.exceptions.HTTPError: 400: JSON schema error with API request '/v2/projects' and JSON data '{'name': 'demo2', '__pydantic_initialised__': True}': Additional properties are not allowed ('__pydantic_initialised__' was unexpected)

**Comment by davidban77** [comment]
Can you post the version of GNS3 you are using and the version of pydantic as well?

**Comment by nguyentheanhhnd** [comment]
I am currently using GNS3 version 2.2.44.1, Python 3.8.10, and Ubuntu 20.04.6 LTS.

**Comment by nguyentheanhhnd** [comment]
I'm also having difficulty with node creation and link creation. Do you have any examples for this? thank you

**Comment by davidban77** [comment]
Here is a link to the documentation for node creation: https://davidban77.github.io/gns3fy/user-guide/#node-creation 

Link creation is just after it.

**Comment by kuuse** [comment]
I had the same error, using 'pip install gns3fy' on Ubuntu 20.04.
A dirty hack is to get the newest version of 'gns3fy.py' from GitHub (either clone the repos or make a raw copy of the file).  
Then overwrite the existing file (which seems to be /usr/local/lib/python3.8/dist-packages/gns3fy/gns3fy.py in your case).

This fixes the 'pydantic_initialised was unexpected' error.

The "proper" solution (according to the documentation) to install the cloned GitHub version is using 'poetry', but this doesn't seem to work with Python 3.8.

**Comment by ipnetxyz** [comment]
> I had the same error, using 'pip install gns3fy' on Ubuntu 20.04. A dirty hack is to get the newest version of 'gns3fy.py' from GitHub (either clone the repos or make a raw copy of the file). Then overwrite the existing file (which seems to be /usr/local/lib/python3.8/dist-packages/gns3fy/gns3fy.py in your case).
> 
> This fixes the 'pydantic_initialised was unexpected' error.
> 
> The "proper" solution (according to the documentation) to install the cloned GitHub version is using 'poetry', but this doesn't seem to work with Python 3.8.

I had the opposite on Ubuntu 24.10...

`pip install gns3fy`

will install by default the latest version from pypi.org, which is 0.8.0

With this version the script was throwing out some error like

`Failed to create project: 400: JSON schema error with API request '/v2/projects' and JSON data '{'name': 'Test01', '__pydantic_initialised__': True}': Additional properties are not allowed ('__pydantic_initialised__' was unexpected)`

What I did was to uninstall the gns3fy and re-install by specifying the version 0.7.2 (which is oddly the last stable version on github)

`pip install gns3fy==0.7.2`

Same script worked without the above error.

HTH
